### ISSUE TITLE
entities that should drop items/experience don't do that in the nether

### ISSUE THREAD

**Issue by kuba26038** [Snownee/PerWorldGameRules#2]
### Mod loader

Forge

### Minecraft version

1.19,2

### Mod version

1.2.0

### Modloader version

forge-43.2.8

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/W600Kf7u

### Issue description

a guy from my discord complained that nether mobs don't have any drops. i decided to investigate, and it turns out no entity that's in the nether dimension drops anything it's supposed to drop, including xp. i tried to trial and error my way to finding the mod that caused this, and i was left with only per dimension game rules.

**Comment by Snownee** [comment]
This is the default setting. You need to change it yourself

**Comment by Onewingseraphim** [comment]
dude why is that the default setting?? Luckily I figured out what mod that was causing it just now but after spending all night/morning today in the Nether we couldn't get any drops and I could not figure out what the deal was...
