### ISSUE TITLE
Undisclosed Dependancy

### ISSUE THREAD

**Issue by Arutheed** [Snownee/PerWorldGameRules#3]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

1.19.2

### Modloader version

Forge: 43.3.2

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Console says it requires kivi.
I recommend mentioning that somewhere.

**Comment by Snownee** [comment]
It has already been mentioned. It just does not show on CurseForge's new site
